# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
