# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_type', models.CharField(max_length=100)),
                ('d_id', models.CharField(max_length=100)),
                ('d_pic', models.ImageField(upload_to='img')),
                ('p_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestlinkBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestlinkCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(blank=True, max_length=100, null=True)),
                ('case_sum', models.TextField(default='null', null=True)),
                ('case_step', models.TextField(blank=True, max_length=4000, null=True)),
                ('case_except', models.TextField(blank=True, null=True)),
                ('internalid', models.CharField(default='null', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TestlinkDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suite_detail', models.TextField(blank=True, default='null')),
                ('suite_id', models.CharField(max_length=100)),
                ('parent_suite_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Ts_app.TestlinkDB')),
            ],
        ),
        migrations.CreateModel(
            name='TestlinkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.CharField(choices=[('Pass', 'pass'), ('Fail', 'fail')], default='Pass', max_length=100)),
                ('result_description', models.TextField(blank=True, max_length=4000, null=True)),
                ('result_pic', models.ImageField(blank=True, null=True, upload_to='img')),
                ('result_video', models.FileField(blank=True, null=True, upload_to='video')),
                ('build_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_report', to='Ts_app.TestlinkBuild')),
                ('test_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_report', to='Ts_app.TestlinkCase')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=1000)),
                ('user_name', models.CharField(max_length=100)),
                ('rent_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='use end time')),
            ],
        ),
        migrations.AddField(
            model_name='testlinkcase',
            name='case_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_case', to='Ts_app.TestlinkDB'),
        ),
    ]
