# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ts_app', '0002_auto_20170328_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='\u8bc4\u8bba\u8005\u540d\u5b57')),
                ('body', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u53d1\u8868\u65f6\u95f4')),
                ('ariticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ts_app.TestlinkCase', verbose_name='\u8bc4\u8bba\u6240\u5c5e\u6587\u7ae0')),
            ],
        ),
    ]
