# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ts_app', '0005_auto_20170508_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_pic', models.ImageField(blank=True, null=True, upload_to='img')),
                ('test_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_pic', to='Ts_app.TestlinkReport')),
            ],
        ),
    ]
